/*  ia6270-ser.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include "ser_dev.h"
#include "ser_cdev.h"

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("ia6270-ser - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "ia6270-ser"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
size_t BufferSize = 65536;
size_t BlockSize = 4096;

module_param(BufferSize, uint, S_IRUGO);
module_param(BlockSize, uint, S_IRUGO);

static irqreturn_t ia6270_ser_irq(int irq, void *lp)
{
	/*
	   printk(KERN_DEBUG "ia6270-ser interrupt\n");
	 */
	ser_event(lp);
	return IRQ_HANDLED;
}

static int ia6270_ser_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct ser_dev *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct ser_dev *) kmalloc(sizeof(struct ser_dev), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate ia6270-ser device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "ia6270-ser: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (r_irq) {
		lp->irq = r_irq->start;
		rc = request_irq(lp->irq, &ia6270_ser_irq, 0, DRIVER_NAME, lp);
		if (rc) {
			dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
				lp->irq);
		}
	}
	else {
		lp->irq = 0;
		dev_info(dev, "no IRQ found\n");
	}

	dev_info(dev,"ia6270-ser at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);

	lp->dev = dev;

	init_waitqueue_head(&lp->r_wait);
	mutex_init(&lp->r_mutex);

	ser_add_cdev(lp);

	return 0;

error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int ia6270_ser_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct ser_dev *lp = dev_get_drvdata(dev);

	ser_del_cdev(lp);
	if(lp->irq) free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id ia6270_ser_of_match[] = {
	{ .compatible = "ia6270,ia6270-ser", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, ia6270_ser_of_match);
#else
#define ia6270_ser_of_match 0
#endif


static struct platform_driver ia6270_ser_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= ia6270_ser_of_match,
	},
	.probe		= ia6270_ser_probe,
	.remove		= ia6270_ser_remove,
};

static int __init ia6270_ser_init(void)
{
	printk("<1>IA6270 SER driver.\n");
	ser_setup_cdev();
	if(platform_driver_register(&ia6270_ser_driver)) {
		goto err0;
	}
	return 0;
err0:
	ser_cleanup_cdev();
	return -1;
}


static void __exit ia6270_ser_exit(void)
{
	platform_driver_unregister(&ia6270_ser_driver);
	ser_cleanup_cdev();
	/*
	   printk(KERN_ALERT "IA6270 SER exit.\n");
	 */
}

module_init(ia6270_ser_init);
module_exit(ia6270_ser_exit);
